name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        run: |
          bundle exec rspec 
